OBJECTS = object/mne_len_nazuvat_atot_file.o object/quad_equ.o object/debug_and_logs.o object/main.o object/func_numbers.o object/input_or_output_function.o object/test.o
CC=g++
CFLAGS= -c -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

kotik.exe: $(OBJECTS)
	$(CC) $(OBJECTS)  -o object/kotik.exe

object/mne_len_nazuvat_atot_file.o: source/mne_len_nazuvat_atot_file.cpp source/mne_len_nazuvat_atot_file.h
	$(CC) $(CFLAGS) $< -o object/$@

object/main.o: source/main.cpp source/test.h source/quad_equ.h source/debug_and_logs.h source/mne_len_nazuvat_atot_file.h
	$(CC) $(CFLAGS) $< -o object/$@

object/quad_equ.o: source/quad_equ.cpp source/input_or_output_function.h source/debug_and_logs.h source/func_numbers.h source/quad_equ.h source/mne_len_nazuvat_atot_file.h
	$(CC) $(CFLAGS) $< -o object/$@

object/func_numbers.o: source/func_numbers.cpp source/quad_equ.h source/func_numbers.h source/mne_len_nazuvat_atot_file.h
	$(CC) $(CFLAGS) $< -o object/$@

object/input_or_output_function.o: source/input_or_output_function.cpp source/input_or_output_function.h source/quad_equ.h
	$(CC) $(CFLAGS) $< -o object/$@

object/debug_and_logs.o: source/debug_and_logs.cpp source/debug_and_logs.h source/mne_len_nazuvat_atot_file.h
	$(CC) $(CFLAGS) $< -o object/$@

object/test.o: source/test.cpp source/test.h source/mne_len_nazuvat_atot_file.h source/quad_equ.h source/func_numbers.h source/debug_and_logs.h source/input_or_output_function.h
	$(CC) $(CFLAGS) $< -o object/$@

docs:
	@doxygen
